### import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully")

Libraries imported successfully

### Load the Dataset

In [2]:
file_path = "../data/raw/yelp_sentiment_master_dataset.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully")

Dataset loaded successfully

### Check First 5 Rows

In [3]:
df.head()

,Sl No,stars_review,text,date,name,categories,city,state,stars_business,review_count,rating_review
0,1,3,"If you decide to eat here, just be aware it is...",07-07-18 22:09,Turning Point of North Wales,"Restaurants, Breakfast & Brunch, Food, Juice B...",North Wales,PA,3.0,169,Neutral
1,2,3,Family diner. Had the buffet. Eclectic assortm...,05-02-14 20:30,Kettle Restaurant,"Restaurants, Breakfast & Brunch",Tucson,AZ,3.5,47,Neutral
2,3,5,"Wow! Yummy, different, delicious. Our favo...",04-01-15 0:01,Zaika,"Halal, Pakistani, Restaurants, Indian",Philadelphia,PA,4.0,181,Positive
3,4,4,Cute interior and owner (?) gave us tour of up...,14-01-17 20:54,Melt,"Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",New Orleans,LA,4.0,32,Positive
4,5,1,I am a long term frequent customer of this est...,23-09-15 23:10,Dmitri's,"Mediterranean, Restaurants, Seafood, Greek",Philadelphia,PA,4.0,273,Negative

### Check Dataset Size

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 14351
Number of columns: 11

In [ ]:
df.shape

(14351, 11)

### Check Column Names

In [6]:
df.columns

Index(['Sl No', 'stars_review', 'text', 'date', 'name', 'categories', 'city',
       'state', 'stars_business', 'review_count', 'rating_review'],
      dtype='object')

### Check Data Types

In [7]:
df.dtypes

Sl No               int64
stars_review        int64
text               object
date               object
name               object
categories         object
city               object
state              object
stars_business    float64
review_count        int64
rating_review      object
dtype: object

### Dataset Information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14351 entries, 0 to 14350
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sl No           14351 non-null  int64
 1   stars_review    14351 non-null  int64
 2   text            14351 non-null  object
 3   date            14351 non-null  object
 4   name            14351 non-null  object
 5   categories      14351 non-null  object
 6   city            14351 non-null  object
 7   state           14351 non-null  object
 8   stars_business  14351 non-null  float64
 9   review_count    14351 non-null  int64
 10  rating_review   14351 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 1.2+ MB

### Missing Values

In [9]:
df.isnull().sum()

Sl No             0
stars_review      0
text              0
date              0
name              0
categories        0
city              0
state             0
stars_business    0
review_count      0
rating_review     0
dtype: int64

### Duplicate Rows

In [10]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

### Basic Statistics

In [11]:
df.describe()

              Sl No  stars_review  stars_business  review_count
count  14351.000000  14351.000000    14351.000000  14351.000000
mean    7176.000000      3.811372        3.759773    463.912898
std     4142.921192      1.322504        0.592612    672.434991
min        1.000000      1.000000        1.000000      5.000000
25%     3588.500000      3.000000        3.500000    100.000000
50%     7176.000000      4.000000        4.000000    238.000000
75%    10763.500000      5.000000        4.000000    541.000000
max    14351.000000      5.000000        5.000000   4554.000000

### Understand stars_review

In [29]:
df["stars_review"].value_counts().sort_index()

stars_review
1    1422
2    1277
3    1795
4    3949
5    5908
Name: count, dtype: int64

In [15]:
df["stars_review"].value_counts(normalize=True).sort_index() * 100

stars_review
1     9.908717
2     8.898335
3    12.507839
4    27.517246
5    41.167863
Name: proportion, dtype: float64

### Understand rating_review

In [16]:
df["rating_review"].value_counts()

rating_review
Positive    9857
Negative    2699
Neutral     1795
Name: count, dtype: int64

In [17]:
df["rating_review"].value_counts(normalize=True) * 100

rating_review
Positive    68.685109
Negative    18.807052
Neutral     12.507839
Name: proportion, dtype: float64

### Check Relationship Between Rating and Sentiment

In [18]:
pd.crosstab(df["stars_review"], df["rating_review"])

rating_review  Negative  Neutral  Positive
stars_review
1                  1422        0         0
2                  1277        0         0
3                     0     1795         0
4                     0        0      3949
5                     0        0      5908

### Inspect Review Text

In [19]:
df["text"].head(10)

0    If you decide to eat here, just be aware it is...
1    Family diner. Had the buffet. Eclectic assortm...
2    Wow!  Yummy, different,  delicious.   Our favo...
3    Cute interior and owner (?) gave us tour of up...
4    I am a long term frequent customer of this est...
5    Amazingly amazing wings and homemade bleu chee...
6    Had a party of 6 here for hibachi. Our waitres...
7    Locals recommended Milktooth, and it's an amaz...
8    Love going here for happy hour or dinner!  Gre...
9    Good food--loved the gnocchi with marinara\nth...
Name: text, dtype: object

In [20]:
df["text"].str.len().describe()

count    14351.000000
mean       536.809003
std        496.934693
min         18.000000
25%        217.000000
50%        382.000000
75%        675.000000
max       4994.000000
Name: text, dtype: float64

### Find Shortest and Longest Reviews

In [22]:
df.loc[df["text"].str.len().idxmin(), "text"]

'its effing subway!'

In [23]:
df.loc[df["text"].str.len().idxmax(), "text"]

'Ohmygod ohmygod ohmygod ohmygod!  I have a new favorite restaurant in town and Home Wine Kitchen is IT.  The schiznIT, in fact.\n\nWe celebrated my birthday at HWK last night.  Originally, we tried to get into Farmhaus (my other fave resto in STL) totally last minute and were told we could either dine outside (in 102 degree weather?  Huh-uh.) or come in at 8:30, which didn\'t jive with our babysitting situation.  So I called HWK, which I\'ve been dying to try since I drove by and spied their sweet space on Manchester.  You people in Maplewood are incredibly lucky to have this restaurant in your midst.  Bow low.\n\nWe were warmly greeted by one of the owners, Josh, and heard about a few revisions to the ever-changing menu.  I like a place that refuses to serve a dish due to sub-par ingredients and yesterday the sardines didn\'t pass the perfection inspection, so they were nixed from the appetizer menu.  No problem for me as I had my eye on the potted pork appetizer, which was outstanding.  The well-seasoned, unctuous spread contrasted nicely with the crisp grilled bread and paired well with pickled radishes, coarse mustard and red onions.  I had a tiny scoop left when the bread ran out and I had it boxed up so none would go to waste.  No potted pork left behind!\n\nSince it\'s the perfect time of year for stellar tomatoes and glorious, sugary corn, my husband and I were torn between the sides of creamed corn and heirloom tomatoes.  We asked our server if he thought we might be overdoing it if we ordered both sides in addition to our entrees (since we weren\'t familiar with HWK\'s portion sizes) and he suggested we\'d do fine with just one side... Buuuuuuut, I said it was BIRTHDAY DINNER and how could we pass up two dishes made up of ingredients so absolutely at their prime?  We couldn\'t.  We ordered the tomatoes and the corn and the chicken and the wild boar.  Thank goodness.  Thank goodness, not because the portions were tiny (in fact, I\'d say they were fairly generous and a really good value), but because the FOOD. WAS. AWESOME.\n\nI couldn\'t help myself when the little cast iron dish holding the creamed corn made it to the table.  I dove right in to the blessed mix of perfect corn, bacon, green onion and leeks and practically shouted to Justin, "You have to try this NOW!"  Part of me wishes I hadn\'t been so exuberant about it--maybe I wouldn\'t have had to share so much.  But damn, that was one of the finest side dishes I\'ve ever had the pleasure of eating.  Ever.  I almost wept with joy.\n\nThe heirloom tomatoes, noted as having thyme, honey and balsamic components on the menu, also arrived in a cast iron dish, which surprised us--I think we were expecting a cold, more salad-like dish.  Don\'t mistake that for disappointment, though, because these tomatoes were also delicious.  Roasted, sweet and juicy, they tasted like the best fresh, chunky tomato soup you can imagine and the bright yellow, orange and red tomatoes just looked cheery.  Does that sound silly?  Probably.  I\'m still giddy from this dinner; indulge me here.\n\nJustin had the wild boar shoulder for dinner, flavored with cumin, orange and currants, slow-cooked in wine and served with fragrant basmati rice.  The boar was topped with orange gremolata, if I\'m not mistaken--a mixture of garlic, parsley and orange zest--and Justin was just blown away by the flavor combination.  He said it reminded him of a dinner we shared at Rick Bayless\' Topolobampo in Chicago, which, if I had to guess, would probably be rated as his #1 dining experience in his 32 years, so this is really high praise for HWK.  It really was delicious.\n\nI had the chicken entree--a perfectly seasoned, crisp skinned, juicy breast and wing accompanied by arugula, bacon and these surprisingly amazing fingerling potatoes.  I was just shocked by how crisp (not burned; crisp) the outsides were and how creamy delicious the insides were.  The arugula gave them a nice nutty taste and the bacon added a nice saltiness to the dish.  I chose wisely.  And I about licked my plate clean.\n\nI was beyond full at this point in the meal and should\'ve passed on dessert, but I was intrigued by the stone fruit dessert with orange cream.  To be fair, I couldn\'t eat much more of anything at all, but this was the only item of the night I wasn\'t head over heels in love with.  The fruit was poached, I believe, with some spices, giving it that Christmas-y, mulled wine sort of taste.  I know lots of people who love that, but it\'s not my favorite.  Maybe I should\'ve tried the goat cheese tart with honey and pistachios, but I thought its richness might totally put me over the edge... Maybe next time. :)\n\nI enjoyed our server, who was knowledgeable, friendly and efficient, and I loved getting to chat with the owners, Josh and Cassie (who is also the chef).  They\'ve done incredible work on the space and made it a unique, intimate place.  I absolutely cannot wait to head back for more fabulous food and support this new restaurant!'

### Check Restaurants

In [24]:
print("Number of unique restaurants:", df["name"].nunique())

Number of unique restaurants: 2526

In [25]:
df["name"].value_counts().head(10)

name
Luke                               187
Mr. B's Bistro                      83
The Pancake Pantry                  82
District Donuts Sliders Brew        81
Surrey's Café & Juice Bar           75
Village Whiskey                     69
Santa Barbara Shellfish Company     66
Prep & Pastry                       64
Baileys' Range                      63
Three Muses                         61
Name: count, dtype: int64

### Check Cities

In [26]:
print("Number of cities:", df["city"].nunique())

Number of cities: 366

In [27]:
df["city"].value_counts().head(10)

city
Philadelphia     2562
New Orleans      1644
Nashville        1111
Tampa             791
Tucson            679
Saint Louis       674
Indianapolis      670
Reno              581
Santa Barbara     411
Edmonton          194
Name: count, dtype: int64

### Check Dates

In [28]:
df["date"].dtype

dtype('O')

In [30]:
print("Unique restaurants:", df["name"].nunique())
print("Unique cities:", df["city"].nunique())

Unique restaurants: 2526
Unique cities: 366

## Phase 2 — Data Cleaning

### Create a Copy

In [32]:
# Create a copy of the original dataset
df_clean = df.copy()

print("Copy created successfully")

Copy created successfully

### Check Text Values

In [33]:
(df_clean["text"].str.strip() == "").sum()

0

In [35]:
df_clean["text"].isnull().sum()

0

### Convert Date

In [36]:
df_clean["date"] = pd.to_datetime(
    df_clean["date"],
    format="%d-%m-%y %H:%M"
)

In [37]:
df_clean["date"].dtype

dtype('<M8[ns]')

### Check Date Conversion

In [38]:
df_clean["date"].head()

0   2018-07-07 22:09:00
1   2014-02-05 20:30:00
2   2015-01-04 00:01:00
3   2017-01-14 20:54:00
4   2015-09-23 23:10:00
Name: date, dtype: datetime64[ns]

### Check Text Data Type

In [39]:
df_clean["text"].dtype

dtype('O')

In [40]:
df_clean["text"].apply(type).value_counts()

text
<class 'str'>    14351
Name: count, dtype: int64

### Check Rating Data Types

In [41]:
print(df_clean["stars_review"].dtype)
print(df_clean["stars_business"].dtype)
print(df_clean["review_count"].dtype)

int64
float64
int64

### Remove Unnecessary Serial Number

In [42]:
df_clean = df_clean.drop(columns=["Sl No"])

### Check the Result

In [43]:
df_clean.head()

,stars_review,text,date,name,categories,city,state,stars_business,review_count,rating_review
0,3,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:00,Turning Point of North Wales,"Restaurants, Breakfast & Brunch, Food, Juice B...",North Wales,PA,3.0,169,Neutral
1,3,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:00,Kettle Restaurant,"Restaurants, Breakfast & Brunch",Tucson,AZ,3.5,47,Neutral
2,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:00,Zaika,"Halal, Pakistani, Restaurants, Indian",Philadelphia,PA,4.0,181,Positive
3,4,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:00,Melt,"Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",New Orleans,LA,4.0,32,Positive
4,1,I am a long term frequent customer of this est...,2015-09-23 23:10:00,Dmitri's,"Mediterranean, Restaurants, Seafood, Greek",Philadelphia,PA,4.0,273,Negative

In [45]:
df_clean.shape

(14351, 10)

### Save Clean Dataset

In [46]:
output_path = "../data/processed/yelp_reviews_cleaned.csv"

df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully