## Phase 3 — NLP Text Preprocessing

### Load Required Libraries

In [1]:
import pandas as pd
import numpy as np
import re
import string

print("Libraries imported successfully")

Libraries imported successfully

### Load Our Clean Dataset

In [2]:
file_path = "../data/processed/yelp_reviews_cleaned.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (14351, 10)

### Check the Text Column

In [3]:
df["text"].head()

0    If you decide to eat here, just be aware it is...
1    Family diner. Had the buffet. Eclectic assortm...
2    Wow!  Yummy, different,  delicious.   Our favo...
3    Cute interior and owner (?) gave us tour of up...
4    I am a long term frequent customer of this est...
Name: text, dtype: object

In [4]:
df["text"].isnull().sum()

0

### Download NLTK Resources

In [5]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("NLTK resources downloaded")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mahad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mahad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mahad\AppData\Roaming\nltk_data...

NLTK resources downloaded

[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mahad\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

### Lowercase Text

In [6]:
df["text_lower"] = df["text"].str.lower()

In [7]:
df[["text", "text_lower"]].head()

,text,text_lower
0,"If you decide to eat here, just be aware it is...","if you decide to eat here, just be aware it is..."
1,Family diner. Had the buffet. Eclectic assortm...,family diner. had the buffet. eclectic assortm...
2,"Wow! Yummy, different, delicious. Our favo...","wow! yummy, different, delicious. our favo..."
3,Cute interior and owner (?) gave us tour of up...,cute interior and owner (?) gave us tour of up...
4,I am a long term frequent customer of this est...,i am a long term frequent customer of this est...

### Remove URLs

In [8]:
def remove_urls(text):
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    return text

In [9]:
sample = "Amazing restaurant! Visit https://example.com"
print(remove_urls(sample))

Amazing restaurant! Visit

### Remove HTML Tags

In [10]:
def remove_html(text):
    text = re.sub(r"<.*?>", "", text)
    return text

In [11]:
sample = "The food was <b>amazing</b>!"
print(remove_html(sample))

The food was amazing!

### Remove Punctuation

In [12]:
def remove_punctuation(text):
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

In [13]:
sample = "Amazing food!!! Very tasty."
print(remove_punctuation(sample))

Amazing food Very tasty

### Tokenization

In [14]:
from nltk.tokenize import word_tokenize

sample = "The food was very delicious and tasty."

tokens = word_tokenize(sample)

print(tokens)

['The', 'food', 'was', 'very', 'delicious', 'and', 'tasty', '.']

### Stopword Removal

In [15]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

print(list(stop_words)[:20])

['theirs', 'no', 'she', 'further', 'other', "i've", 'wouldn', 'again', 'than', 'its', 'your', 'these', 'were', 'because', 'mustn', "he'd", 'it', 'nor', 'am', "shouldn't"]

In [16]:
sample = "The food was very delicious and tasty."

tokens = word_tokenize(sample.lower())

filtered_tokens = [
    word for word in tokens
    if word.isalpha() and word not in stop_words
]

print(filtered_tokens)

['food', 'delicious', 'tasty']

### Lemmatization

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [18]:
words = ["restaurants", "dogs", "better"]

for word in words:
    print(word, "→", lemmatizer.lemmatize(word))

restaurants → restaurant
dogs → dog
better → better

### Create the Main Preprocessing Function

In [19]:
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords and non-alphabetic tokens
    tokens = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]

    # Lemmatize
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    # Join tokens
    return " ".join(tokens)

### Test the Function

In [20]:
sample_review = df["text"].iloc[2]

print("Original:")
print(sample_review)

print("\nProcessed:")
print(preprocess_text(sample_review))

Original:
Wow!  Yummy, different,  delicious.   Our favorite is the lamb curry and korma.  With 10 different kinds of naan!!!  Don't let the outside deter you (because we almost changed our minds)...go in and try something new!   You'll be glad you did!

Processed:
wow yummy different delicious favorite lamb curry korma different kind naan dont let outside deter almost changed mindsgo try something new youll glad

In [21]:
# First, we should verify the preprocessing function on 5–10 examples.

for i in range(5):
    print("ORIGINAL:")
    print(df["text"].iloc[i])
    
    print("\nPROCESSED:")
    print(preprocess_text(df["text"].iloc[i]))
    
    print("\n" + "="*80 + "\n")

ORIGINAL:
If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience.

The food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.

PROCESSED:
decide eat aware going take hour beginning end tried multiple time want like location nj never bad experience food good take long time come waitstaff young usually pleasant many experience spent way long waiting usually opt another diner restaurant weekend order done quicker

================================================================================

ORIGINAL:
Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served all day long. Friendly, attentive staff. Good place for a casual relaxed meal with no expectations. Next to the Clarion Hotel.

PROCESSED:
family diner buffet eclectic assortment large chicken leg fried jalapeño tamale two rolled grape leaf fresh melon good lot mexican choice also menu breakfast served day long friendly attentive staff good place casual relaxed meal expectation next clarion hotel

================================================================================

ORIGINAL:
Wow!  Yummy, different,  delicious.   Our favorite is the lamb curry and korma.  With 10 different kinds of naan!!!  Don't let the outside deter you (because we almost changed our minds)...go in and try something new!   You'll be glad you did!

PROCESSED:
wow yummy different delicious favorite lamb curry korma different kind naan dont let outside deter almost changed mindsgo try something new youll glad

================================================================================

ORIGINAL:
Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I liked. Needed something else...pepper jelly maybe. Would like to see more menu options added such as salads w fun cheeses. Lots of beer and wine as well as limited cocktails. Next time I will try one of the draft wines.

PROCESSED:
cute interior owner gave u tour upcoming patiorooftop area great beautiful day like today cheese curd good filling really like sandwich come w salad esp eating many curd onion gruyere tomato sandwich wasnt much cheese liked needed something elsepepper jelly maybe would like see menu option added salad w fun cheese lot beer wine well limited cocktail next time try one draft wine

================================================================================

ORIGINAL:
I am a long term frequent customer of this establishment. I just went in to order take out (3 apps) and was told they're too busy to do it. Really? The place is maybe half full at best. Does your dick reach your ass? Yes? Go fuck yourself! I'm a frequent customer AND great tipper. Glad that Kanella just opened. NEVER going back to dmitris!

PROCESSED:
long term frequent customer establishment went order take apps told theyre busy really place maybe half full best dick reach as yes go fuck im frequent customer great tipper glad kanella opened never going back dmitris

================================================================================

### Improve Stopword Handling

In [22]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

# Keep words that can change sentiment
negation_words = {
    "no",
    "not",
    "nor",
    "never",
    "neither",
    "hardly",
    "barely",
    "scarcely"
}

stop_words = stop_words - negation_words

In [23]:
print("not" in stop_words)
print("never" in stop_words)
print("no" in stop_words)

False
False
False

### Improve the Preprocessing Function

In [24]:
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Expand common contractions
    contractions = {
        "don't": "do not",
        "doesn't": "does not",
        "didn't": "did not",
        "isn't": "is not",
        "wasn't": "was not",
        "weren't": "were not",
        "can't": "can not",
        "couldn't": "could not",
        "wouldn't": "would not",
        "shouldn't": "should not",
        "won't": "will not",
        "would've": "would have",
        "could've": "could have",
        "should've": "should have"
    }

    for contraction, replacement in contractions.items():
        text = text.replace(contraction, replacement)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove punctuation
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # Tokenization
    tokens = word_tokenize(text)

    # Remove stopwords but keep negation words
    tokens = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]

    # Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    # Join tokens
    return " ".join(tokens)

### Test Negation

In [25]:
test_reviews = [
    "The food is good.",
    "The food is not good.",
    "I never liked this restaurant.",
    "I did not like the service.",
    "I don't want to come back."
]

for review in test_reviews:
    print("Original :", review)
    print("Processed:", preprocess_text(review))
    print("-" * 60)

Original : The food is good.
Processed: food good
------------------------------------------------------------
Original : The food is not good.
Processed: food not good
------------------------------------------------------------
Original : I never liked this restaurant.
Processed: never liked restaurant
------------------------------------------------------------
Original : I did not like the service.
Processed: not like service
------------------------------------------------------------
Original : I don't want to come back.
Processed: not want come back
------------------------------------------------------------

### Now Process the Entire Dataset

In [26]:
df["clean_text"] = df["text"].apply(preprocess_text)

In [27]:
df[["text", "clean_text"]].head()

,text,clean_text
0,"If you decide to eat here, just be aware it is...",decide eat aware going take hour beginning end...
1,Family diner. Had the buffet. Eclectic assortm...,family diner buffet eclectic assortment large ...
2,"Wow! Yummy, different, delicious. Our favo...",wow yummy different delicious favorite lamb cu...
3,Cute interior and owner (?) gave us tour of up...,cute interior owner gave u tour upcoming patio...
4,I am a long term frequent customer of this est...,long term frequent customer establishment went...

In [33]:
df[["text", "clean_text", "rating_review"]].head()

,text,clean_text,rating_review
0,"If you decide to eat here, just be aware it is...",decide eat aware going take hour beginning end...,Neutral
1,Family diner. Had the buffet. Eclectic assortm...,family diner buffet eclectic assortment large ...,Neutral
2,"Wow! Yummy, different, delicious. Our favo...",wow yummy different delicious favorite lamb cu...,Positive
3,Cute interior and owner (?) gave us tour of up...,cute interior owner gave u tour upcoming patio...,Positive
4,I am a long term frequent customer of this est...,long term frequent customer establishment went...,Negative

In [28]:
print("Original columns:", df.shape[1])
print("Number of reviews:", df.shape[0])

Original columns: 12
Number of reviews: 14351

### Check Empty Processed Reviews

In [29]:
empty_reviews = (df["clean_text"].str.strip() == "").sum()

print("Empty processed reviews:", empty_reviews)

Empty processed reviews: 0

### Save the NLP Dataset

In [30]:
output_path = "../data/processed/yelp_reviews_nlp.csv"

df.to_csv(output_path, index=False)

print("NLP dataset saved successfully")

NLP dataset saved successfully